compile:
	npx hardhat compile

launch:
	npx hardhat node

deploy:
	npx hardhat run --network localhost scripts/deploy.ts

c=
typechain:
	npx typechain --target web3-v1  './artifacts/contracts/${c}.sol/${c}.json'
